"""add procedures and chat spaces

Revision ID: 36f04146ef00
Revises: fd9e5f01a612
Create Date: 2026-10-07 16:28:47.775054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36f04146ef00'
down_revision: Union[str, Sequence[str], None] = 'fd9e5f01a612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

field_kind = postgresql.ENUM('text', 'email', 'phone', 'rut', 'number', 'date', name='field_kind', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    field_kind.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_thread',
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_chat_thread_last_message_at'), 'chat_thread', ['last_message_at'], unique=False)
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('content_hash', sa.Text(), sa.Computed("md5(name || E'\\n' || steps)", persisted=True), nullable=False),
    sa.Column('embedded_hash', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['business_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_area_id'), 'procedure', ['area_id'], unique=False)
    op.create_index('ix_procedure_embedding', 'procedure', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('procedure_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', field_kind, nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procedure_id', 'name')
    )
    # El correo general pasa a ser el space general: un correo no se puede convertir en un space, así que las filas
    # existentes se borran y el responsable de contenidos carga los spaces.
    op.execute("DELETE FROM fallback_contact")
    op.rename_table('fallback_contact', 'fallback_space')
    op.execute("ALTER TABLE fallback_space RENAME CONSTRAINT fallback_contact_pkey TO fallback_space_pkey")
    op.drop_column('fallback_space', 'email')
    op.add_column('fallback_space', sa.Column('chat_space', sa.String(length=255), nullable=False))
    op.add_column('business_area', sa.Column('chat_space', sa.String(length=255), nullable=True))
    op.drop_column('business_area', 'owner_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_area', sa.Column('owner_email', sa.VARCHAR(length=320), autoincrement=False, nullable=True))
    op.drop_column('business_area', 'chat_space')
    op.execute("DELETE FROM fallback_space")
    op.drop_column('fallback_space', 'chat_space')
    op.add_column('fallback_space', sa.Column('email', sa.VARCHAR(length=320), nullable=False))
    op.execute("ALTER TABLE fallback_space RENAME CONSTRAINT fallback_space_pkey TO fallback_contact_pkey")
    op.rename_table('fallback_space', 'fallback_contact')
    op.drop_table('procedure_field')
    op.drop_index('ix_procedure_embedding', table_name='procedure', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_procedure_area_id'), table_name='procedure')
    op.drop_table('procedure')
    op.drop_index(op.f('ix_chat_thread_last_message_at'), table_name='chat_thread')
    op.drop_table('chat_thread')
    # ### end Alembic commands ###
    field_kind.drop(op.get_bind())
