"""create assistant tables

Revision ID: 6d7d25d1a640
Revises: 3cedeabf6f74
Create Date: 2026-10-09 14:05:44.369082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d7d25d1a640'
down_revision: Union[str, Sequence[str], None] = '3cedeabf6f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Crearla requiere superusuario: si el usuario de la app no lo es, un DBA la crea antes y esto no hace nada.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('agent_prompt',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('business_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scope', sa.Enum('internal', 'external', name='area_scope'), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tools', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('web', 'google_chat', name='channel'), nullable=False),
    sa.Column('external_key', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_key')
    )
    op.create_index(op.f('ix_conversation_last_message_at'), 'conversation', ['last_message_at'], unique=False)
    op.create_table('faq_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['business_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'name')
    )
    op.create_index(op.f('ix_faq_category_area_id'), 'faq_category', ['area_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_conversation_id_id', 'message', ['conversation_id', 'id'], unique=False)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('content_hash', sa.Text(), sa.Computed("md5(question || E'\\n' || answer)", persisted=True), nullable=False),
    sa.Column('embedded_hash', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['faq_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_category_id'), 'faq', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faq_category_id'), table_name='faq')
    op.drop_table('faq')
    op.drop_index('ix_message_conversation_id_id', table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_faq_category_area_id'), table_name='faq_category')
    op.drop_table('faq_category')
    op.drop_index(op.f('ix_conversation_last_message_at'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_table('business_area')
    op.drop_table('agent_prompt')
    # drop_table no borra los enums; sin esto, un nuevo upgrade falla porque los tipos ya existen.
    # La extensión vector se mantiene: otras bases o un DBA pueden depender de ella.
    for enum_name in ("message_role", "channel", "area_scope"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
