"""add tools access mcp and jira boards

Revision ID: 85edb5a46f4b
Revises: f1add1f645e2
Create Date: 2026-10-09 16:32:37.502979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85edb5a46f4b'
down_revision: Union[str, Sequence[str], None] = 'f1add1f645e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_board',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('mcp_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('credential_key', sa.String(length=100), nullable=True),
    sa.Column('allowed_tools', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('area_member',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['business_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_id', 'email')
    )
    op.add_column('business_area', sa.Column('mcp_servers', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_area', 'mcp_servers')
    op.drop_table('area_member')
    op.drop_table('mcp_server')
    op.drop_table('jira_board')
    # ### end Alembic commands ###
