"""create web chat tables

Revision ID: d57dd2a1f838
Revises: fd1bce01b4ea
Create Date: 2026-10-07 13:03:11.672899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd57dd2a1f838'
down_revision: Union[str, Sequence[str], None] = 'fd1bce01b4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

web_phase = postgresql.ENUM('bot', 'offering_human', 'collecting_contact', 'queued', 'live', name='web_phase', create_type=False)
live_chat_status = postgresql.ENUM('waiting', 'assigned', 'closed', name='live_chat_status', create_type=False)
close_reason = postgresql.ENUM('executive', 'customer_left', 'executive_timeout', 'schedule_end', name='close_reason', create_type=False)
message_sender = postgresql.ENUM('customer', 'executive', name='message_sender', create_type=False)
enums = (web_phase, live_chat_status, close_reason, message_sender)


def upgrade() -> None:
    """Upgrade schema."""
    for enum in enums:
        enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phase', web_phase, server_default='bot', nullable=False),
    sa.Column('contact_attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('pending_question', sa.Text(), nullable=True),
    sa.Column('connected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_web_session_connected_last_seen_at', 'web_session', ['connected', 'last_seen_at'], unique=False)
    op.create_index(op.f('ix_web_session_last_message_at'), 'web_session', ['last_message_at'], unique=False)
    op.create_table('live_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_session_id', sa.Uuid(), nullable=False),
    sa.Column('status', live_chat_status, nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_contact', sa.String(length=320), nullable=False),
    sa.Column('pending_question', sa.Text(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executive_disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', close_reason, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ),
    sa.ForeignKeyConstraint(['web_session_id'], ['web_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_chat_assigned_executive', 'live_chat', ['executive_id'], unique=False, postgresql_where=sa.text("status = 'assigned'"))
    op.create_index('ix_live_chat_status_created_at', 'live_chat', ['status', 'created_at'], unique=False)
    op.create_index('ux_live_chat_open_web_session', 'live_chat', ['web_session_id'], unique=True, postgresql_where=sa.text("status <> 'closed'"))
    op.create_table('live_chat_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('live_chat_id', sa.Integer(), nullable=False),
    sa.Column('sender', message_sender, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['live_chat_id'], ['live_chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_chat_message_chat_id', 'live_chat_message', ['live_chat_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_live_chat_message_chat_id', table_name='live_chat_message')
    op.drop_table('live_chat_message')
    op.drop_index('ux_live_chat_open_web_session', table_name='live_chat', postgresql_where=sa.text("status <> 'closed'"))
    op.drop_index('ix_live_chat_status_created_at', table_name='live_chat')
    op.drop_index('ix_live_chat_assigned_executive', table_name='live_chat', postgresql_where=sa.text("status = 'assigned'"))
    op.drop_table('live_chat')
    op.drop_index(op.f('ix_web_session_last_message_at'), table_name='web_session')
    op.drop_index('ix_web_session_connected_last_seen_at', table_name='web_session')
    op.drop_table('web_session')
    # ### end Alembic commands ###
    for enum in enums:
        enum.drop(op.get_bind())
