"""make property key unique

Revision ID: d7c550c19a14
Revises: 53e8891ae5d9
Create Date: 2026-10-06 17:58:11.827009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c550c19a14'
down_revision: Union[str, Sequence[str], None] = '53e8891ae5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('property_key_key', 'property', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('property_key_key', 'property', type_='unique')
    # ### end Alembic commands ###
