"""create business tables

Revision ID: ddcc2f8e20b1
Revises: 3cedeabf6f74
Create Date: 2026-10-07 13:00:07.462915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ddcc2f8e20b1'
down_revision: Union[str, Sequence[str], None] = '3cedeabf6f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Lo usan business_area y fallback_contact: se crea y se borra una sola vez, fuera de create_table.
area_scope = postgresql.ENUM('internal', 'external', name='area_scope', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # Requiere que el servidor tenga pgvector instalado; ver R1 del plan de la spec 001.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    area_scope.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_prompt',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('business_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scope', area_scope, nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('owner_email', sa.String(length=320), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'name')
    )
    op.create_table('fallback_contact',
    sa.Column('scope', area_scope, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('scope')
    )
    op.create_table('holiday',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('official_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_schedule',
    sa.Column('weekday', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.CheckConstraint('opens_at < closes_at', name='service_schedule_hours_check'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='service_schedule_weekday_check'),
    sa.PrimaryKeyConstraint('weekday')
    )
    op.create_table('faq_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['business_area.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_category_area_id'), 'faq_category', ['area_id'], unique=False)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('content_hash', sa.Text(), sa.Computed("md5(question || E'\\n' || answer)", persisted=True), nullable=False),
    sa.Column('embedded_hash', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['faq_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_category_id'), 'faq', ['category_id'], unique=False)
    op.create_index('ix_faq_embedding', 'faq', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_faq_embedding', table_name='faq', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_faq_category_id'), table_name='faq')
    op.drop_table('faq')
    op.drop_index(op.f('ix_faq_category_area_id'), table_name='faq_category')
    op.drop_table('faq_category')
    op.drop_table('service_schedule')
    op.drop_table('official_channel')
    op.drop_table('holiday')
    op.drop_table('fallback_contact')
    op.drop_table('business_area')
    op.drop_table('agent_prompt')
    # ### end Alembic commands ###
    area_scope.drop(op.get_bind())
    # La extensión vector no se borra: crearla o borrarla exige superusuario y puede usarla otro esquema.
